title: A Culinary
logo: /assets/img/logo.png
description: Cooking till perfect!
footer: © A Culinary 2020
google_analytics: 
plugins:
- jekyll-redirect-from
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-feed



